matrix_groups:
  fertilizer:
    canonical_units: ["mg/kg", "ug/kg"]
  soil:
    canonical_units: ["mg/kg", "ug/kg"]
  plant:
    canonical_units: ["mg/kg", "ug/kg"]
  food:
    canonical_units: ["mg/kg", "ug/kg"]
  feces:
    canonical_units: ["mg/kg", "ug/kg"]
  blood:
    canonical_units: ["ug/L"]
